services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-southeast-1
      
  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=batch_processing_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/batch_processing_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - AWS_S3_ENDPOINT=http://localstack:4566
    depends_on:
      - mysql
      - localstack
      
  web:
    build:
      context: ./web
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
